### PR TITLE
Use python3 (tiny change)

### PR DESCRIPTION
**Pull request by pb-cdunn**
These scripts use python3. (And that's good, for snakemake needs python3
too.) Within PacBio, I use `module load python/3`. That's designed to
allow us to have both python2.7 and python3.x in the same environment,
so it leaves `python` alone. In other words:
```
% module load python/3
% which python3
/mnt/software/p/python/3.6.4/bin/python3
% which python
/usr/bin/python
```
So it's helpful to me if these use python3 explicitly.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Oh, I saw `print()` in these, so I assumed they were python3. Ivan says python2 also works, so let's discard this PR. nvm

**Comment by zeeev** [comment]
Hi Chris,

Sorry for the late reply, but I see you've sorted it out. Let us know if anything else comes up in your review.

Best,

Zev

**Comment by pb-cdunn** [comment]
There is one unrelated change you might want: In your Makefile, `echo -e` will interpret `\n` as an actual newline!

**Comment by zeeev** [comment]
@pb-cdunn thanks for the catch.

**Pull request closed without merging**
